Catch the case where the compilation fails because of a `NoClassDefFoundError`. It may happen when an annotation processor is present but has a dependency which is missing.