Remove the `multirelease-patterns/packaging-plugin` test because it was testing another plugin than this project. It was testing `pw.krejci:multi-release-jar-maven-plugin`, which fails with `NoSuchMethodError` with Maven 4-RC3. That external project may need to be updated for Maven 4.